# syntax=docker/dockerfile:1.4
FROM node:19-alpine3.16

RUN mkdir /app
WORKDIR /app

# install app dependencies
COPY package.json ./
COPY package-lock.json ./

RUN npm install

COPY . /app

EXPOSE 8000

CMD ["npm", "run", "dev"]
